FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

ENV UPLOADS_PATH="temp"

CMD ["flask", "run", "--host=0.0.0.0"]