FROM python:latest

WORKDIR /src

RUN apt-get update && apt-get install -y \
    gnupg \
    curl \
    unixodbc \
    unixodbc-dev \
    gcc \
    g++ \
    && rm -rf /var/lib/apt/lists/*
ENV ACCEPT_EULA=Y
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && apt-get install -y msodbcsql18 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

ENV UPLOADS_PATH="temp"
ENV DATABASE_ODBC_CONNECTION_STRING="Driver={ODBC Driver 18 for SQL Server};Server=tcp:ccsqlserver6r8acbg.database.windows.net,1433;Database=ccsqldatabase;Uid=sqladmin;Pwd=Synapse!96;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"

CMD ["python", "app.py"]
